name: CV_CapturableZone
version: ${project.version}
main: com.motompro.cv_capturablezone.CV_CapturableZone
authors: [TomMo]
description: Un plugin qui ajoute des zones capturables.
commands:
  capturablezone:
    description: Commande du mod CapturableZone.
